# Generated by Django 3.2.16 on 2022-11-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablebookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Denied')], default=0),
        ),
    ]
